//! Pattern C cross-language interop test vectors.
//!
//! The fixtures in `pattern_c_interop_vectors.json` are generated by
//! `tests/generate_vectors/main.go` against the Go SDK at
//! `kennguy3n/zk-object-fabric/encryption/client_sdk/`. Regenerate
//! with:
//!
//! ```sh
//! cd tests/generate_vectors
//! go run . > ../../crates/core/tests/pattern_c_interop_vectors.json
//! ```
//!
//! The Rust implementation in `crate::crypto::convergent` must
//! produce **bit-identical** output to the Go SDK. These vectors
//! are the Phase 0 contract; any change in the Go SDK that breaks a
//! vector should be matched by a deliberate, reviewed update here.

use kchat_core::crypto::content_hash::content_hash;
use kchat_core::crypto::convergent::{
    decrypt_object_pattern_c, derive_convergent_dek, derive_convergent_nonce,
    encrypt_object_pattern_c,
};

const VECTORS_JSON: &str = include_str!("pattern_c_interop_vectors.json");

#[derive(serde::Deserialize)]
struct Vector {
    name: String,
    content_hash_hex: String,
    tenant_id: String,
    plaintext_hex: String,
    chunk_size: usize,
    dek_hex: String,
    nonce0_hex: String,
    ciphertext_hex: String,
}

fn vectors() -> Vec<Vector> {
    serde_json::from_str(VECTORS_JSON).expect("vectors JSON parses")
}

#[test]
fn vectors_file_is_non_empty() {
    let v = vectors();
    assert!(!v.is_empty(), "expected at least one interop vector");
}

#[test]
fn content_hash_matches_go_blake3() {
    for v in vectors() {
        let plaintext = hex::decode(&v.plaintext_hex).unwrap();
        let want = hex::decode(&v.content_hash_hex).unwrap();
        let got = content_hash(&plaintext);
        assert_eq!(
            got.as_slice(),
            want.as_slice(),
            "vector {}: BLAKE3(plaintext) mismatch",
            v.name,
        );
    }
}

#[test]
fn derive_convergent_dek_matches_go() {
    for v in vectors() {
        let content_hash = hex::decode(&v.content_hash_hex).unwrap();
        let want_dek = hex::decode(&v.dek_hex).unwrap();
        let dek = derive_convergent_dek(&content_hash, &v.tenant_id).unwrap();
        assert_eq!(
            dek.as_bytes().as_slice(),
            want_dek.as_slice(),
            "vector {}: DEK mismatch",
            v.name,
        );
    }
}

#[test]
fn derive_convergent_nonce_matches_go() {
    for v in vectors() {
        let dek = hex::decode(&v.dek_hex).unwrap();
        let want_nonce = hex::decode(&v.nonce0_hex).unwrap();
        let got = derive_convergent_nonce(&dek, 0, 24).unwrap();
        assert_eq!(got, want_nonce, "vector {}: chunk-0 nonce mismatch", v.name);
    }
}

#[test]
fn encrypt_object_pattern_c_matches_go() {
    for v in vectors() {
        let plaintext = hex::decode(&v.plaintext_hex).unwrap();
        let dek = hex::decode(&v.dek_hex).unwrap();
        let want_ct = hex::decode(&v.ciphertext_hex).unwrap();
        let got = encrypt_object_pattern_c(&plaintext, &dek, v.chunk_size).unwrap();
        assert_eq!(
            got, want_ct,
            "vector {}: ciphertext mismatch (Go SDK)",
            v.name
        );
    }
}

#[test]
fn decrypt_go_ciphertext_round_trips() {
    for v in vectors() {
        let plaintext = hex::decode(&v.plaintext_hex).unwrap();
        let dek = hex::decode(&v.dek_hex).unwrap();
        let ciphertext = hex::decode(&v.ciphertext_hex).unwrap();
        let got = decrypt_object_pattern_c(&ciphertext, &dek, v.chunk_size).unwrap();
        assert_eq!(
            got, plaintext,
            "vector {}: decrypt of Go ciphertext did not yield plaintext",
            v.name,
        );
    }
}
